config/routes.rb
Files::Application.routes.draw do
  resources :db_structures

  resources :file_folders

  devise_for :users
  resources :files_roots do  
    collection  do
      post :add_folder     
    end    
  end

  root "files_roots#index"

  

end

app/models/file_folder.rb
class FileFolder < ActiveRecord::Base
  belongs_to :folder


  def store(io_file)
     begin
       ActiveRecord::Base.transaction do
         self.name = io_file.original_filename
         self.save!
         root = User.current.folder_root_paths.first
         path = File.join(Folder::USER_FILE_ROOT, root.id.to_s, self.id.to_s)
         self.path = path
         self.save!
  	     File.open(path, "wb") { |f| f.write(io_file.read) }
       end
  	   return true
     rescue Exception => e
       return false
     end
  end
end

app/controllers/file_folders_controller.rb
class FileFoldersController < ApplicationController
  before_action :set_current_user#:set_file_folder, only: [:show, :edit, :update, :destroy]

  # GET /file_folders
  # GET /file_folders.json
  def index
    @file_folders = FileFolder.all
  end

  # GET /file_folders/1
  # GET /file_folders/1.json
  def show
  end

  # GET /file_folders/new
  def new
    @file_folder = FileFolder.new
  end

  # GET /file_folders/1/edit
  def edit
  end

  # POST /file_folders
  # POST /file_folders.json
  def create
    #@file_folder = FileFolder.new(file_folder_params)
    @folder = current_user.folders.where("id = ?", params[:current_folder_id]).first
    @files = @folder.file_folders.build   
    io_file = params[:file]
    respond_to do |format|
      if @files.store(io_file)
        @files = [] << @files
        format.js {render "files_list", status: 200}
      else
        format.js {render js: "alert('Could not create file", status: 400}
      end      
    end    
  end

  # PATCH/PUT /file_folders/1
  # PATCH/PUT /file_folders/1.json
  def update
    respond_to do |format|
      if @file_folder.update(file_folder_params)
        format.html { redirect_to @file_folder, notice: 'File folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @file_folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_folders/1
  # DELETE /file_folders/1.json
  def destroy
    @file_folder.destroy
    respond_to do |format|
      format.html { redirect_to file_folders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_folder
      @file_folder = FileFolder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_folder_params
      params[:file_folder]
    end
end

app/helpers/file_folders_helper.rb
module FileFoldersHelper
end

app/views/file_folders/_files_list.html.erb
<% unless @files.nil? %>
  <% @files.each do |file| %>
    <li id="<%=file.id%>"><%= link_to file.name, "###", remote: true, id: file.id, :class => "icon-file" %>
    </li>
  <% end %> 
<% end %>

app/views/file_folders/_form.html.erb
<%= form_for(@file_folder) do |f| %>
  <% if @file_folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_folder.errors.count, "error") %> prohibited this file_folder from being saved:</h2>

      <ul>
      <% @file_folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_folders/edit.html.erb
<h1>Editing file_folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_folder %> |
<%= link_to 'Back', file_folders_path %>

app/views/file_folders/index.html.erb
<h1>Listing file_folders</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @file_folders.each do |file_folder| %>
      <tr>
        <td><%= link_to 'Show', file_folder %></td>
        <td><%= link_to 'Edit', edit_file_folder_path(file_folder) %></td>
        <td><%= link_to 'Destroy', file_folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File folder', new_file_folder_path %>

app/views/file_folders/new.html.erb
<h1>New file_folder</h1>

<%= render 'form' %>

<%= link_to 'Back', file_folders_path %>

app/views/file_folders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_file_folder_path(@file_folder) %> |
<%= link_to 'Back', file_folders_path %>