config/routes.rb
Files::Application.routes.draw do
  resources :db_structures

  resources :file_folders

  devise_for :users
  resources :files_roots do  
    collection  do
      post :add_folder     
    end    
  end

  root "files_roots#index"

  

end

app/models/files_root.rb
class FilesRoot < ActiveRecord::Base
end

app/controllers/files_roots_controller.rb
class FilesRootsController < ApplicationController
  before_action :authenticate_user!, :set_current_user
  before_action :set_files_root, only: [:show, :edit, :update, :destroy]
  

  # GET /files_roots
  # GET /files_roots.json
  def index
    #@files_roots = FilesRoot.all

    @root = current_user.folders.where("id == folder_id").first
 
    unless @root.nil?
      @folders = @root.subfolders.where("id <> folder_id")
      @files = @root.file_folders
      @folder_new = current_user.folders.new
    else
      respond_to do |format|
        format.html{render 'create_root'}
      end      
      return
    end
    
  end

  # GET /files_roots/1
  # GET /files_roots/1.json
  def show
    @root = current_user.folders.find(params[:id])
    @folders = @root.subfolders
    @files = @root.file_folders
    respond_to do |format|
      format.js{render 'folder_content_list', status: 200}
    end
  end

  # GET /files_roots/new
  def new
    @files_root = FilesRoot.new
  end

  # GET /files_roots/1/edit
  def edit
  end

  # POST /files_roots
  # POST /files_roots.json
  def create
    @files_root = FilesRoot.new(files_root_params)

    respond_to do |format|
      if @files_root.save
        format.html { redirect_to @files_root, notice: 'Files root was successfully created.' }
        format.json { render action: 'show', status: :created, location: @files_root }
      else
        format.html { render action: 'new' }
        format.json { render json: @files_root.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_folder

    @folder = current_user.folders.where("id == ?", params[:current_folder_id]).first
    @add_folder = @folder.subfolders.new
    @add_folder.name = params[:folder][:name] 
    @add_folder.user_id = current_user.id

    respond_to do |format|
      if @add_folder.save
        format.js{render 'add_to_folder', status: 200}
      else
        format.js{render js: "alert('Could not create folder');", status: 400}
      end      
    end   
  end

  # PATCH/PUT /files_roots/1
  # PATCH/PUT /files_roots/1.json
  def update
    respond_to do |format|
      if @files_root.update(files_root_params)
        format.html { redirect_to @files_root, notice: 'Files root was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @files_root.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /files_roots/1
  # DELETE /files_roots/1.json
  def destroy
    #@files_root.destroy
    @delete_folder_id = params[:id]
    current_user.folders.find(@delete_folder_id).destroy
    respond_to do |format|
      format.js{ render "delete_from_content_folder", status: 200}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_files_root
      #@files_root = FilesRoot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def files_root_params
      #params[:files_root]
    end
end

app/helpers/files_roots_helper.rb
module FilesRootsHelper
end

app/views/files_roots/_folder_content_list.html.erb
  <li class="nav-header"><%= locals[:title] %></li>
<% @folders.each do |folder| %>
  <li id="<%=folder.id%>"><%= link_to folder.name, files_root_path(folder.id), remote: true, id: folder.id, :class => "icon-folder-close" %>
  </li>
<% end %>

app/views/files_roots/_form.html.erb
<%= form_for(@folder_new, url: add_folder_files_roots_path, remote: true) do |f| %>
  <%= hidden_field_tag :current_folder_id, "" %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/files_roots/_upload_file.html.erb
<%= form_tag  file_folders_path, method: :post, id: "upload_file", remote: true, multipart: true do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token, "data-remote" => true %>
  <%= hidden_field_tag :current_folder_id, "", "data-remote" => true %>
  <%= file_field_tag :file, "data-remote" => true %>
  </br>
  </br>
  <div class="actions">
    <%= submit_tag "Upload", "data-remote" => true, remote: true %>
  </div>
<% end %>

app/views/files_roots/create_root.html.erb
<div class="container-fluid">
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#"></a>
      <ul class="nav folder_nav">
        <li class="active">
          <a id="nav_create_root" href="###">Create Root</a>
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span4" style="background: #C84189;">
      <!--Sidebar content-->
      <ul id="root_content_list" class="nav nav-list">
      </ul>    
      
    </div>
    <div id="folder_content" class="span8" style="background: white;">
      <!--Body content-->
      <ul id="folder_content_list" class="nav nav-list">
        
      </ul>      
    </div>
  </div>
</div>

app/views/files_roots/edit.html.erb
<h1>Editing files_root</h1>

<%= render 'form' %>

<%= link_to 'Show', @files_root %> |
<%= link_to 'Back', files_roots_path %>

app/views/files_roots/index.html.erb
<div class="container-fluid">
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#"><%= @root.name.upcase %></a>
      <ul class="nav folder_nav">
        <li class="active">
          <a id="nav_new_folder" href="###" current_folder_id="<%= @root.id %>">New Folder</a>
        </li>
        <li>
          <a id="nav_upload_file" class="upload_file_dialog" href="###" current_folder_id="<%= @root.id %>">Upload File</a>
        </li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul id="folders_breadcrumb" class="breadcrumb">
        <li><a href="#">Домой</a> <span class="divider">/</span></li>
        <li><a href="#">Библиотека</a> <span class="divider">/</span></li>
        <li class="active">Данные</li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span4" style="background: #C84189;">
      <!--Sidebar content-->
      <ul id="root_content_list" class="nav nav-list">
        <a class="icon-refresh" href="###"> ROOT</a>
        <%= render 'folder_content_list', :locals => {:title => "ROOT"} %>
      </ul> 
      <ul>
        <li class="icon-trash"><a href="###">Trash</a></li>
      </ul>   
      
    </div>
    <div id="folder_content" current_folder_id="<%= @root.id %>" class="span8" style="background: white;">
      <!--Body content-->
      <ul id="folder_content_list" class="nav nav-list">
        <%= render 'folder_content_list', locals: {title: @root.name.upcase} %>
      </ul> 
        <ul id="files_list" class="nav nav-list">
          <%= render 'file_folders/files_list' %>
        </ul>            
    </div>
  </div>
</div>


<div id="new_folder_dialog" style="display: none;">
  <%= render 'form' %>
</div>
<div id="upload_file_dialog" style="display: none;">
  <%= render 'upload_file' %>
</div>

  <ul class="dropdown-menu menu_over_folder" role="menu" aria-labelledby="dropdownMenu" slected_folder_id="" >
    <li><%= link_to "Delete", files_root_path(0), method: :delete, remote: true, tabindex: "-1", :class => "menu_over_folder_delete" %></li>
    <li><a tabindex="-1" href="#">Rename</a></li>
    <li><a tabindex="-1" href="#"></a></li>
    <li class="divider"></li>
    <li><a tabindex="-1" href="#">Property</a></li>
  </ul>

  <ul class="dropdown-menu menu_over_file" role="menu" aria-labelledby="dropdownMenu" slected_file_id="" >
    <li><%= link_to "Delete", "###", method: :delete, remote: true, tabindex: "-1", :class => "menu_over_folder_delete" %></li>
    <li><a tabindex="-1" href="#">Rename</a></li>
    <li><a tabindex="-1" href="#"></a></li>
    <li class="divider"></li>
    <li><a tabindex="-1" href="#">Property</a></li>
  </ul>

app/views/files_roots/new.html.erb
<h1>New files_root</h1>

<%= render 'form' %>

<%= link_to 'Back', files_roots_path %>

app/views/files_roots/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_files_root_path(@files_root) %> |
<%= link_to 'Back', files_roots_path %>