config/routes.rb
Files::Application.routes.draw do
  resources :db_structures

  resources :file_folders

  devise_for :users
  resources :files_roots do  
    collection  do
      post :add_folder     
    end    
  end

  root "files_roots#index"

  

end

app/models/db_structure.rb
class DbStructure < ActiveRecord::Base
end

app/controllers/db_structures_controller.rb
class DbStructuresController < ApplicationController
  layout "db_structure"
  #before_action :set_db_structure, only: [:show, :edit, :update, :destroy]

  # GET /db_structures
  # GET /db_structures.json
  def index
    @db_structures = DbStructure.all

    Rails.application.eager_load! unless Rails.configuration.cache_classes

    
  end

  # GET /db_structures/1
  # GET /db_structures/1.json
  def show
  end

  # GET /db_structures/new
  def new
    @db_structure = DbStructure.new
  end

  # GET /db_structures/1/edit
  def edit
  end

  # POST /db_structures
  # POST /db_structures.json
  def create
    @db_structure = DbStructure.new(db_structure_params)

    respond_to do |format|
      if @db_structure.save
        format.html { redirect_to @db_structure, notice: 'Db structure was successfully created.' }
        format.json { render action: 'show', status: :created, location: @db_structure }
      else
        format.html { render action: 'new' }
        format.json { render json: @db_structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /db_structures/1
  # PATCH/PUT /db_structures/1.json
  def update
    respond_to do |format|
      if @db_structure.update(db_structure_params)
        format.html { redirect_to @db_structure, notice: 'Db structure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @db_structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /db_structures/1
  # DELETE /db_structures/1.json
  def destroy
    @db_structure.destroy
    respond_to do |format|
      format.html { redirect_to db_structures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_db_structure
      @db_structure = DbStructure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def db_structure_params
      params[:db_structure]
    end
end

app/helpers/db_structures_helper.rb
module DbStructuresHelper
end

app/views/db_structures/_form.html.erb
<%= form_for(@db_structure) do |f| %>
  <% if @db_structure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@db_structure.errors.count, "error") %> prohibited this db_structure from being saved:</h2>

      <ul>
      <% @db_structure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/db_structures/edit.html.erb
<h1>Editing db_structure</h1>

<%= render 'form' %>

<%= link_to 'Show', @db_structure %> |
<%= link_to 'Back', db_structures_path %>

app/views/db_structures/index.html.erb
<h1>Listing db_structures</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @db_structures.each do |db_structure| %>
      <tr>
        <td><%= link_to 'Show', db_structure %></td>
        <td><%= link_to 'Edit', edit_db_structure_path(db_structure) %></td>
        <td><%= link_to 'Destroy', db_structure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Db structure', new_db_structure_path %>

<div id="table_contener" class="well well-large table_structure">
  <div class="table" style="position: relative; width:100px; height:100px; ">
    <table class="table table-bordered">
      <thead>
        <tr class="">
          <th>has_many</th><th>:table_name</th><th>dependent: :destroy</th>
          <th>hhhh</th>
          <th>class:</th>
        </tr>
        <tr>
          <th>has_one</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <tr>
          <th>belongs_to</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </tbody>
      <caption>TABLE_NAME: NAME</caption>
    </table>
  </div>
</div>

app/views/db_structures/new.html.erb
<h1>New db_structure</h1>

<%= render 'form' %>

<%= link_to 'Back', db_structures_path %>

app/views/db_structures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_db_structure_path(@db_structure) %> |
<%= link_to 'Back', db_structures_path %>